I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/actTwo.rpy", line 10, in script
    de "So this is the room in question..."
NameError: name 'detective_name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/actTwo.rpy", line 10, in script
    de "So this is the room in question..."
  File "D:\Ren'Py\renpy-7.4.9-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\Ren'Py\renpy-7.4.9-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "D:\Ren'Py\renpy-7.4.9-sdk\renpy\character.py", line 1248, in __call__
    who = renpy.python.py_eval(who)
  File "D:\Ren'Py\renpy-7.4.9-sdk\renpy\python.py", line 1083, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Ren'Py\renpy-7.4.9-sdk\renpy\python.py", line 1076, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'detective_name' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.2.22081402
The Triar Incident v0.0.10
Thu Sep 29 23:12:38 2022
