I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/actTwo.rpy", line 64, in script
    $ kt_villain = kt_villian + 1
  File "game/scripts/actTwo.rpy", line 64, in <module>
    $ kt_villain = kt_villian + 1
NameError: name 'kt_villian' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/actTwo.rpy", line 64, in script
    $ kt_villain = kt_villian + 1
  File "D:\Ren'Py\renpy-7.4.9-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Ren'Py\renpy-7.4.9-sdk\renpy\python.py", line 1052, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/actTwo.rpy", line 64, in <module>
    $ kt_villain = kt_villian + 1
NameError: name 'kt_villian' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.2.22081402
Project Avadakadabra v0.0.5
Mon Sep 19 19:47:24 2022
